name: Docker Lint CI

on:
  push:
  pull_request:

jobs:
  lint-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint

      - name: Run Hadolint
        run: |
          ./hadolint app/Dockerfile || true